DFRobotMaqueenPlusV2.I2CInit()
soundExpression.hello.play()
basic.showIcon(IconNames.SmallHeart)
basic.showIcon(IconNames.Heart)
basic.showIcon(IconNames.SmallHeart)
basic.showIcon(IconNames.Heart)
basic.forever(function () {
    basic.showIcon(IconNames.Skull)
    DFRobotMaqueenPlusV2.setIndexColor(0, 0x0000ff)
    DFRobotMaqueenPlusV2.setIndexColor(1, 0xff0000)
    DFRobotMaqueenPlusV2.setIndexColor(2, 0x0000ff)
    DFRobotMaqueenPlusV2.setIndexColor(3, 0xff0000)
    basic.pause(350)
    DFRobotMaqueenPlusV2.setIndexColor(0, 0xff0000)
    DFRobotMaqueenPlusV2.setIndexColor(1, 0x0000ff)
    DFRobotMaqueenPlusV2.setIndexColor(2, 0xff0000)
    DFRobotMaqueenPlusV2.setIndexColor(3, 0x0000ff)
    basic.pause(350)
})
